name       : perl-sub-install
version    : '0.929'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Sub-Install-0.929.tar.gz : 80b1e281d8cd3b2b31dac711f5c8a1657a87cd80bbe69af3924bcbeb4e5db077
homepage   : https://metacpan.org/pod/Sub::Install
license    : Artistic-2.0
component  : programming.perl
summary    : Install subroutines into packages easily
description: |
    Install subroutines into packages easily
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
