name       : perl-sub-install
version    : 0.928
release    : 7
source     :
    - http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS/Sub-Install-0.928.tar.gz : 61e567a7679588887b7b86d427bc476ea6d77fffe7e0d17d640f89007d98ef0f
license    : Artistic-2.0
component  : programming.perl
summary    : Install subroutines into packages easily
description: |
    Install subroutines into packages easily
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
